spring.application.name=TfgApiSpringBoot


# Configuración de la Base de Datos (Railway)
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# JPA / Hibernate
# 'update' crea las tablas automáticamente en MySQL basándose en tus clases de Kotlin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto de la API (opcional, Railway suele usar el 8080 por defecto)
server.port=8080